config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  get '/welcome/:first_name', to: 'welcome#hello'
  get '/team', to: 'us#team'
  get '/contact', to: 'us#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip, optional:true
    belongs to :commentable, polymorphic: true, optional: true
    belongs_to :user
    has_many :likes
    has_many :comments, as :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :gossip_tags
    has_many :tags
    has_many :comments
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :recipient_lists
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
	has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        puts Gossip.all
    end
end

app/controllers/us_controller.rb
class UsController < ApplicationController
 def team
 end

 def contact
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def hello
        puts "#" * 60
        @first_name = params[:first_name]
        puts "#" * 60
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/us_helper.rb
module UsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/welcome.html.erb
<h1>THE GOSSIP PROJECT<h1>
<h2>Ici, tu pourras parler sur tes copines à coeur ouvert. Fais juste attention: t'es pas anonyme.<h2>
<p>D'ailleurs, voici une liste de tous les potins jusqu'à aujourd'hui:</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <!-- Latest compiled and minified CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

   <body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">THE GOSSIP PROJECT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" >  <%= link_to "Team", team_path %>  </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" > <%= link_to "Contact", contact_path %>  </a>
      </li>
    </ul>
  </div>
</nav>
</nav>
</body>
<%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>

app/views/us/contact.html.erb
<h1> Nous contacter !</h1>
<p> Si tu veux nous contacter, appelles au 06.72.09.46.42, c'est mon numéro wallaye. </p>

app/views/us/team.html.erb
<h1>Bonjour ! </h1>
<p>Petite présentation de notre belle équipe !</p>
<p>Ah non j'suis tout seul pcq j'suis un putain d'antisocial, mais dans ma tête on est 46 et on est tous solidaire ! :) </p>

app/views/welcome/hello.html.erb
<h1> Bienvenue <%= @first_name %> </h1>
<p>Ici, c'est notre super-méga-joli site de potins</p></br>
<p>J'espère qu'il te plait!</p>